### ISSUE TITLE
Suggestions on adding Applicative and Alternative custom operators

### ISSUE THREAD

**Issue by inamiy** [thoughtbot/Runes#65]
Hi :smile: 

I recently created Swift parser combinator library called https://github.com/tryswift/TryParsec (inspired by Argo :sparkles:), and I'm planning to use Runes to keep same operator precedences as discussing in https://github.com/tryswift/TryParsec/pull/11.

Specifically, I want Runes to have following declarations:

``` swift
/// Haskell `infixl 3`.
/// - Note: typelift/Operadics use `precedence 120` for `infixr 2` and `precedence 130` for `infixl 4`.
infix operator <|>  { associativity left precedence 125 }

/// Haskell `infixl 4`.
infix operator <*   { associativity left precedence 140 }

/// Haskell `infixl 4`.
infix operator *>   { associativity left precedence 140 }
```

I also found [typelift/Operadics](https://github.com/typelift/Operadics) useful, but `infix operator <|>` was still missing.

Since Runes seems more de-facto library, I would like to ask what will be the good solution.
Thanks!

**Comment by gfontenot** [comment]
I would very much be interested in a pull request with this implemented!

I feel like we discussed adding `<|>` here a while ago, but didn't think it was super useful for `Optional` (because :sparkles:magic  optional wrapping:sparkles:) and so didn't follow through with  an implementation. We're currently using it in Argo though, so I don't see any reason to _not_ add it here.

**Comment by inamiy** [comment]
Thank you for positive feedback :smile: 
I send PR in https://github.com/thoughtbot/Runes/pull/66, but still having precedence issue, so please tell me your thoughts on this!

**Comment by gfontenot** [comment]
Oh hey this is done in #66 coooooooooool!
